[tool.poetry]
name = "start-sql"
version = "0.1.0"
description = ""
authors = ["Kuprin Aleksandr <freeman8901@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.5"
python-dotenv = "^1.2.1"
pandas = "^2.3.3"
openpyxl = "^3.1.5"
psycopg2 = "^2.9.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
